"""cascade delete for runs and news

Revision ID: 3d9eab625881
Revises: bee1cc536d2d
Create Date: 2026-09-05 09:55:07.737233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9eab625881'
down_revision: Union[str, Sequence[str], None] = 'bee1cc536d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('news_run_id_fkey'), 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('runs_project_id_fkey'), 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(op.f('runs_project_id_fkey'), 'runs', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key(op.f('news_run_id_fkey'), 'news', 'runs', ['run_id'], ['id'])
    # ### end Alembic commands ###
